### ISSUE TITLE
PDF tools on Alfred 4 doesn't work

### ISSUE THREAD

**Issue by manil88j86** [xilopaint/alfred-pdf-tools#18] opened 2022-05-24 10:35 UTC
**Version numbers**
macOS Catalina Version 10.15.7
Alfred 4.6.6 [1303]

**Description of the bug**
When I try to run Alfred PDF Tools I get an error loading Python lib.
Is it because (as you can see in the error code) it says Python was built for Mac OS X 12.0? How do I fix this?

**To reproduce**
The same error seems to occur with any of the workflows. The example below if for when I try to merge two PDFs.

**Debugger screenshot and copied debugger output**
![image](https://user-images.githubusercontent.com/106078457/170250627-83f65596-7ccb-4e79-9365-7507f0e1c602.png)

[12:19:39.699] Logging Started...
[12:19:46.854] Alfred PDF Tools[[File Action](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3EA6A91646-8622-45F4-B763-4A6ACBAFD08C)] Processing complete
[12:19:46.857] Alfred PDF Tools[[File Action](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3EA6A91646-8622-45F4-B763-4A6ACBAFD08C)] Passing output '(
    "/Users/joannamain/Library/Mobile Documents/com~apple~CloudDocs/ForjoFurniture/Brochure/brochure.pdf",
    "/Users/joannamain/Library/Mobile Documents/com~apple~CloudDocs/ForjoFurniture/Brochure/CT-580-580-O Drawing .pdf"
)' to [Arg and Vars](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3E2412A11E-00A7-400B-90FD-BAEBC00EA23A)
[12:19:46.858] Alfred PDF Tools[[Arg and Vars](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3E2412A11E-00A7-400B-90FD-BAEBC00EA23A)] Processing complete
[12:19:46.859] Alfred PDF Tools[[Arg and Vars](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3E2412A11E-00A7-400B-90FD-BAEBC00EA23A)] Passing output '' to [Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECEBD82BA-6268-426D-9BFE-62BCD4C27471)
[12:19:49.770] Alfred PDF Tools[[Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECEBD82BA-6268-426D-9BFE-62BCD4C27471)] Processing complete
[12:19:49.773] Alfred PDF Tools[[Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECEBD82BA-6268-426D-9BFE-62BCD4C27471)] Passing output 'test' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECF8EFD70-FC46-46DA-85B7-5C40E39C3722)
[12:19:51.095] ERROR: Alfred PDF Tools[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECF8EFD70-FC46-46DA-85B7-5C40E39C3722)] [4265] Error loading Python lib '/var/folders/rs/9pnx32rj6ql4pmg8sxbdt0100000gn/T/_MEIKNEPnB/Python': dlopen: dlopen(/var/folders/rs/9pnx32rj6ql4pmg8sxbdt0100000gn/T/_MEIKNEPnB/Python, 10): Symbol not found: _preadv
  Referenced from: /var/folders/rs/9pnx32rj6ql4pmg8sxbdt0100000gn/T/_MEIKNEPnB/Python (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by manil88j86** [comment] 2022-05-25 11:22
Sorry, I have edited it! I hope it is acceptable now?

**Comment by xilopaint** [comment] 2022-05-25 12:11
> Is it because (as you can see in the error code) it says Python was built for Mac OS X 12.0? How do I fix this?

It seems so. You can try to clone te repo and run the `make` command at the root of the repository to build the workflow file in your system. But I'm not sure if it will work.

As [PyPDF2](https://github.com/py-pdf/PyPDF2) development evolves I may decide to rewrite this workflow using it again. In this case the compatibility issue should be fixed.

**Comment by xilopaint** [comment] 2022-05-25 13:42
Actually, in the current state the workflow is compatible with macOS Monterey. It's by design, not really an issue. If I adopt `PyPDF2` again it should be compatible with any macOS version running Alfred 4 and I will let you know.

**Closed by xilopaint** 2022-05-25 13:42 UTC
Labels: invalid

**Comment by xilopaint** [comment] 2022-06-29 20:12
> Thank you; it would be great if you could please let me know if and when you do decide to fix this compatibility issue

The workflow has been rewritten with PyPDF2 so I believe it's compatible with Catalina as of v4.
